-- Close fresh-project RLS gaps for electronic agreements and weekly billing.
-- The legacy `admin` role is named `court_owner` in the current role model.

-- Historical receipt policies used `bucket_id <> 'receipts'`. Because RLS
-- policies are permissive, those predicates opened every non-receipts bucket
-- to anon/authenticated. Direct receipt access is default-deny; the Edge
-- Function uses service_role and does not need a storage.objects policy.
drop policy if exists receipts_no_select on storage.objects;
drop policy if exists receipts_no_insert on storage.objects;
drop policy if exists receipts_no_update on storage.objects;
drop policy if exists receipts_no_delete on storage.objects;

-- --------------------------------------------------------------------------
-- Agreements
-- --------------------------------------------------------------------------

alter table public.agreements enable row level security;

drop policy if exists "users_read_own_agreement" on public.agreements;
drop policy if exists agreements_select_own_or_admin on public.agreements;
drop policy if exists agreements_insert_own_or_admin on public.agreements;
drop policy if exists agreements_update_own_or_admin on public.agreements;
drop policy if exists agreements_delete_admin on public.agreements;

-- Every dashboard role can read only its own acceptance. The system owner is
-- the only role with global agreement oversight because agreement rows contain
-- legal-name, signature, IP, and user-agent data.
create policy agreements_select_own_or_admin
on public.agreements
for select
to authenticated
using (
  (
    user_id = auth.uid()::text
    and public.current_dashboard_role() in ('owner', 'court_owner', 'staff')
  )
  or public.current_dashboard_role() = 'owner'
);

-- This permits the client's ON CONFLICT (user_id, version) upsert while
-- preventing an ordinary authenticated account from accepting for anyone else.
create policy agreements_insert_own_or_admin
on public.agreements
for insert
to authenticated
with check (
  (
    user_id = auth.uid()::text
    and public.current_dashboard_role() in ('owner', 'court_owner', 'staff')
  )
  or public.current_dashboard_role() = 'owner'
);

create policy agreements_update_own_or_admin
on public.agreements
for update
to authenticated
using (
  (
    user_id = auth.uid()::text
    and public.current_dashboard_role() in ('owner', 'court_owner', 'staff')
  )
  or public.current_dashboard_role() = 'owner'
)
with check (
  (
    user_id = auth.uid()::text
    and public.current_dashboard_role() in ('owner', 'court_owner', 'staff')
  )
  or public.current_dashboard_role() = 'owner'
);

create policy agreements_delete_admin
on public.agreements
for delete
to authenticated
using (public.current_dashboard_role() = 'owner');

-- --------------------------------------------------------------------------
-- Weekly fees
-- --------------------------------------------------------------------------

alter table public.weekly_fees enable row level security;

drop policy if exists weekly_fees_select_auth on public.weekly_fees;
drop policy if exists weekly_fees_insert_auth on public.weekly_fees;
drop policy if exists weekly_fees_update_auth on public.weekly_fees;
drop policy if exists weekly_fees_delete_auth on public.weekly_fees;
drop policy if exists weekly_fees_select_billing on public.weekly_fees;
drop policy if exists weekly_fees_insert_owner on public.weekly_fees;
drop policy if exists weekly_fees_update_billing on public.weekly_fees;
drop policy if exists weekly_fees_update_owner on public.weekly_fees;
drop policy if exists weekly_fees_delete_owner on public.weekly_fees;

-- System owners administer every statement. Court owners only see statements
-- addressed to their Auth account; staff have no weekly-billing read surface.
create policy weekly_fees_select_billing
on public.weekly_fees
for select
to authenticated
using (
  public.current_dashboard_role() = 'owner'
  or (
    public.current_dashboard_role() = 'court_owner'
    and court_owner_user_id = auth.uid()::text
  )
);

-- Statements are generated by the system-owner billing panel.
create policy weekly_fees_insert_owner
on public.weekly_fees
for insert
to authenticated
with check (public.current_dashboard_role() = 'owner');

-- Direct statement mutation is a system-owner operation. Court owners submit
-- only the four remittance-evidence fields through submit_weekly_fee_payment().
create policy weekly_fees_update_owner
on public.weekly_fees
for update
to authenticated
using (public.current_dashboard_role() = 'owner')
with check (public.current_dashboard_role() = 'owner');

-- Removing a financial statement remains a system-owner operation.
create policy weekly_fees_delete_owner
on public.weekly_fees
for delete
to authenticated
using (public.current_dashboard_role() = 'owner');

-- A court owner may move only their own sent/overdue statement to submitted
-- and may write only remittance evidence. SECURITY DEFINER is intentional: the
-- table UPDATE policy above is owner-only, while this function enforces the
-- narrower court-owner transition atomically.
create or replace function public.submit_weekly_fee_payment(
  p_fee_id uuid,
  p_submitted_ref text,
  p_submitted_note text default null,
  p_submitted_proof_url text default null
)
returns table (
  fee_id uuid,
  status text,
  submitted_at timestamptz,
  submitted_ref text
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.current_dashboard_role();
  v_actor uuid := auth.uid();
  v_ref text := btrim(coalesce(p_submitted_ref, ''));
  v_note text := nullif(btrim(coalesce(p_submitted_note, '')), '');
  v_proof text := coalesce(p_submitted_proof_url, '');
  v_submitted_at timestamptz := statement_timestamp();
begin
  if v_role <> 'court_owner' or v_actor is null then
    raise exception 'A court-owner account is required.' using errcode = '42501';
  end if;

  if length(v_ref) not between 1 and 100 or v_ref ~ '[[:cntrl:]<>]' then
    raise exception 'A valid remittance reference is required.' using errcode = '22023';
  end if;
  if v_note is not null and length(v_note) > 2000 then
    raise exception 'The remittance note is too long.' using errcode = '22023';
  end if;
  if octet_length(v_proof) not between 32 and 6000000
     or v_proof !~* '^data:image/(png|jpe?g|webp|gif);base64,[A-Za-z0-9+/=[:space:]]+$' then
    raise exception 'A valid receipt image is required.' using errcode = '22023';
  end if;

  return query
  update public.weekly_fees as wf
     set status = 'submitted',
         submitted_at = v_submitted_at,
         submitted_ref = v_ref,
         submitted_note = v_note,
         submitted_proof_url = v_proof
   where wf.id = p_fee_id
     and wf.court_owner_user_id = v_actor::text
     and wf.status in ('sent', 'overdue')
  returning wf.id, wf.status, wf.submitted_at, wf.submitted_ref;

  if not found then
    raise exception 'Statement is unavailable or cannot be submitted.'
      using errcode = 'P0002';
  end if;
end;
$$;

revoke all on function public.submit_weekly_fee_payment(uuid, text, text, text)
  from public;
grant execute on function public.submit_weekly_fee_payment(uuid, text, text, text)
  to authenticated;

notify pgrst, 'reload schema';
